### ISSUE TITLE
Test with zero wins results in bad message to user

### ISSUE THREAD

**Issue by eriklong95** [Emilostuff/ordle#1]
If a bot completes a test with zero wins, the user is presented with a stack trace that ends in a ZeroDivisionError. This error apparently stems from a calculation which tries to find the average number of attempts in games won.

Perhaps, one could present the user with a more descriptive message in this case. Something like "Sorry, your bot was shit."

**Comment by Emilostuff** [comment]
Thanks for pointing it out! It has been fixed now, although I refrained from introducing any trash talk, despite being quite an amusing feature :)
